export const eventNames = {
  CARD_SELECTED: 'CARD_SELECTED',
  CARD_DESELECTED: 'CARD_DESELECTED',
  CARD_LIMIT_REACHED: 'CARD_LIMIT_REACHED',
  CARD_ALREADY_INCLUDED: 'CARD_ALREADY_INCLUDED'
};

export const localStorageKeys = {
  POKEMON_DECK: 'POKEMON_DECK',
}